[package]
name = "the-humble-building"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
winit = { version="0.30" }
env_logger = "0.10"
log = "0.4"
wgpu = "30.0"
pollster = "0.3"
bytemuck = { version = "1.24", features = ["derive"] }
cgmath = "0.18"
dear-imgui-rs = "0.16.0-alpha.2"
dear-imgui-wgpu = "0.16.0-alpha.2"
dear-imgui-winit = "0.16.0-alpha.2"

[patch.crates-io]
dear-imgui-rs = { git = "https://github.com/jamsterwes/dear-imgui-rs.git", branch = "fix/use-getcurrentwindowread-scope-snapshot" }
